pipeline {
    agent any

    environment {
        AWS_REGION = "ap-south-1"
        REPO_NAME = "notes-app"
        ACCOUNT_ID = credentials('aws-account-id') 
        IMAGE_TAG = "latest"
        KUBECONFIG_CRED = credentials('kubeconfig')
    }

    stages {

        stage('Checkout') {
            steps {
                git url: 'https://github.com/YOUR_USERNAME/notes-app.git', branch: 'main'
            }
        }

        stage('Install Python dependencies') {
            steps {
                sh 'pip install -r backend/requirements.txt'
            }
        }

        stage('Run Unit Tests') {
            steps {
                sh 'pytest backend/tests -q'
            }
        }

        stage('Docker Build') {
            steps {
                sh """
                    docker build -t $REPO_NAME:$IMAGE_TAG ./backend
                """
            }
        }

        stage('ECR Login') {
            steps {
                sh """
                    aws ecr get-login-password --region $AWS_REGION \
                    | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
                """
            }
        }

        stage('Docker Push') {
            steps {
                sh """
                    docker tag $REPO_NAME:$IMAGE_TAG \
                    $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG

                    docker push \
                    $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG
                """
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                withCredentials([file(credentialsId: 'kubeconfig', variable: 'KCONFIG')]) {
                    sh 'mkdir -p ~/.kube'
                    sh 'cp $KCONFIG ~/.kube/config'
                }

                sh """
                    kubectl set image deployment/notes-app-deploy \
                    notes-app=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG -n notes-app
                """
            }
        }
    }
}
